<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Appusergroup_model extends CI_Model
{

    public $table = 'appusergroup';
    public $id = 'UserGroupID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('UserGroupID,ParentUserGroupID,UserGroupName,IsActive,IsInternal,UserType');
        $this->datatables->from('appusergroup');
        //add this line for join
        //$this->datatables->join('table2', 'appusergroup.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('appusergroup/read/$1'),'Read')." | ".anchor(site_url('appusergroup/update/$1'),'Update')." | ".anchor(site_url('appusergroup/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'UserGroupID');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('UserGroupID', $q);
	$this->db->or_like('ParentUserGroupID', $q);
	$this->db->or_like('UserGroupName', $q);
	$this->db->or_like('IsActive', $q);
	$this->db->or_like('IsInternal', $q);
	$this->db->or_like('UserType', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('UserGroupID', $q);
	$this->db->or_like('ParentUserGroupID', $q);
	$this->db->or_like('UserGroupName', $q);
	$this->db->or_like('IsActive', $q);
	$this->db->or_like('IsInternal', $q);
	$this->db->or_like('UserType', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Appusergroup_model.php */
/* Location: ./application/models/Appusergroup_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-24 13:35:45 */
/* http://harviacode.com */