<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Appuser_model extends CI_Model
{

    public $table = 'appuser';
    public $id = 'UserID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('UserID,UserGroupID,ParentUserID,UserLoginID,UserName,NPP,Password,SRLanguage,EmailAddress,PhoneNumber,ActiveDate,ExpireDate,IsActive,AreaGroupID,AreaID,AgencyID,EmployeeID,PhotoFilePath,PhotoFileName,IconPhotoFilePath');
        $this->datatables->from('appuser');
        //add this line for join
        //$this->datatables->join('table2', 'appuser.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('appuser/read/$1'),'Read')." | ".anchor(site_url('appuser/update/$1'),'Update')." | ".anchor(site_url('appuser/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'UserID');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('UserID', $q);
	$this->db->or_like('UserGroupID', $q);
	$this->db->or_like('ParentUserID', $q);
	$this->db->or_like('UserLoginID', $q);
	$this->db->or_like('UserName', $q);
	$this->db->or_like('NPP', $q);
	$this->db->or_like('Password', $q);
	$this->db->or_like('SRLanguage', $q);
	$this->db->or_like('EmailAddress', $q);
	$this->db->or_like('PhoneNumber', $q);
	$this->db->or_like('ActiveDate', $q);
	$this->db->or_like('ExpireDate', $q);
	$this->db->or_like('IsActive', $q);
	$this->db->or_like('AreaGroupID', $q);
	$this->db->or_like('AreaID', $q);
	$this->db->or_like('AgencyID', $q);
	$this->db->or_like('EmployeeID', $q);
	$this->db->or_like('PhotoFilePath', $q);
	$this->db->or_like('PhotoFileName', $q);
	$this->db->or_like('IconPhotoFilePath', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('UserID', $q);
	$this->db->or_like('UserGroupID', $q);
	$this->db->or_like('ParentUserID', $q);
	$this->db->or_like('UserLoginID', $q);
	$this->db->or_like('UserName', $q);
	$this->db->or_like('NPP', $q);
	$this->db->or_like('Password', $q);
	$this->db->or_like('SRLanguage', $q);
	$this->db->or_like('EmailAddress', $q);
	$this->db->or_like('PhoneNumber', $q);
	$this->db->or_like('ActiveDate', $q);
	$this->db->or_like('ExpireDate', $q);
	$this->db->or_like('IsActive', $q);
	$this->db->or_like('AreaGroupID', $q);
	$this->db->or_like('AreaID', $q);
	$this->db->or_like('AgencyID', $q);
	$this->db->or_like('EmployeeID', $q);
	$this->db->or_like('PhotoFilePath', $q);
	$this->db->or_like('PhotoFileName', $q);
	$this->db->or_like('IconPhotoFilePath', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Appuser_model.php */
/* Location: ./application/models/Appuser_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-24 13:35:45 */
/* http://harviacode.com */