<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sales_model extends CI_Model
{

    public $table = 'sales';
    public $id = 'idsales';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idsales,npp,nama_sales,email,notelp,password');
        $this->datatables->from('sales');
        //add this line for join
        //$this->datatables->join('table2', 'sales.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('sales/read/$1'),'Read')." | ".anchor(site_url('sales/update/$1'),'Update')." | ".anchor(site_url('sales/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'idsales');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idsales', $q);
	$this->db->or_like('npp', $q);
	$this->db->or_like('nama_sales', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('notelp', $q);
	$this->db->or_like('password', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idsales', $q);
	$this->db->or_like('npp', $q);
	$this->db->or_like('nama_sales', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('notelp', $q);
	$this->db->or_like('password', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sales_model.php */
/* Location: ./application/models/Sales_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-07 10:42:58 */
/* http://harviacode.com */